variables:
    DOCKER_DRIVER: overlay

stages:
    - build
    - deploy


build-image:
    tags:
        - tester
    image: docker:latest
    stage: build
    services:
        -   name: docker:dind
    script:
        - docker-compose -f docker-compose-build.yml build --no-cache arete_integration_tests
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker push $DOCKER_USER/arete_integration_tests:$CI_COMMIT_REF_NAME
    only:
        - dev
        - master


run-tests:
    tags:
        - tester
    image: docker:latest
    stage: deploy
    services:
        -   name: docker:dind
    script:
        - docker run -e ARETE_TOKEN=$ARETE_TOKEN $DOCKER_USER/arete_integration_tests:$CI_COMMIT_REF_NAME
    only:
        - dev
        - master