version: '3.4'

services:

    arete_integration_tests:
        image: ${DOCKER_USER}/arete_integration_tests:latest
        container_name: arete_integration_tests
        build:
            context: .
